# Generated by Django 4.1 on 2022-10-28 17:40

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('telefono', models.IntegerField()),
                ('fecha', models.DateField()),
                ('hora', models.TimeField(verbose_name=builtins.min)),
                ('cantidadPersonas', models.IntegerField()),
                ('estadoReserva', models.IntegerField(choices=[[0, 'RESERVADO'], [1, 'COMPLETADA'], [2, 'ANULADA'], [3, 'NO ASISTEN']])),
                ('observaccion', models.TextField()),
            ],
        ),
    ]
