# Generated by Django 4.1 on 2022-10-28 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appReserva', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='hora',
            field=models.TimeField(),
        ),
    ]
